<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.anna</groupId>
    <artifactId>detector-de-camada-de-aplicacao-2</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <decycle-maven-plugin.version>0.11.0</decycle-maven-plugin.version>
    </properties>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>de.obqo.decycle</groupId>
                    <artifactId>decycle-maven-plugin</artifactId>
                    <version>${decycle-maven-plugin.version}</version>
                    <executions>
                        <execution>
                            <goals>
                                <goal>check</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <slicings>
                            <slicing>
                                <name>dependencies</name>
                                <patterns>
                                    <pattern>com.anna.controller.*=controller,</pattern>
                                    <pattern>com.anna.services.*=service,</pattern>
                                    <pattern>com.anna.domain.*=domain</pattern>
                                    <pattern>com.anna.persistence.*=persistence</pattern>
                                </patterns>
                                <constraints>
                                    <allow>controller, service, domain</allow>
                                    <allow>service, persistence, domain</allow>
                                    <allow>controller, persistence</allow>
                                    <allow>dto, domain</allow>
                                    <allow>restclient, controller</allow>
                                    <allow>restclient, service</allow>
                                    <allow>restclient, persistence</allow>
                                    <allow>restclient, domain</allow>
                                </constraints>
                            </slicing>
                        </slicings>
                    </configuration>
                </plugin>                
            </plugins>
        </pluginManagement>

        <plugins>
            <plugin>
                <groupId>de.obqo.decycle</groupId>
                <artifactId>decycle-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>