name: Java CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Java ${{ matrix.java }}
    strategy:
      matrix:
        java: [21]

    steps:
      - uses: actions/checkout@v4.2.0

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4.5.0
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: Cache local Maven repository
        uses: actions/cache@v4.2.0
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests
        run: mvn test

      - name: Set up Graphviz
        uses: ts-graphviz/setup-graphviz@v2.0.2

      - name: Validate
        run: ./mvnw -B clean validate

      - name: Pmd
        run: ./mvnw -B -Ppmd validate

      - name: Tests
        run: ./mvnw -B verify

      - name: Checkstyle
        run: ./mvnw -B -Pcheckstyle validate

      - name: Cpd
        run: ./mvnw -B -Pcpd validate

      - name: Plantuml
        run: ./mvnw -B -Pplantuml generate-test-sources

      - name: Upload UML Diagrams #fazer o upload dos diagramas UML
        uses: actions/upload-artifact@v4.4.3 #usar a action upload-artifact
        with:
          name: uml-diagrams # Nome do artefato
          path: target/generate-diagrams/classes.png # Caminho para o arquivo a ser enviado

      - name: Decycle
        run: ./mvnw -B -Pdecycle -DskipTests verify

      - name: Duplicate
        run: ./mvnw -B -Pduplicate -DskipTests verify

      - name: Spotbugs
        run: ./mvnw -B -Pspotbugs -DskipTests process-test-classes

      - name: SonarQube Analysis
        run: mvn sonar:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      - name: Set NVD API Key
        run: echo "NVD_API_KEY=${{ secrets.NVD_API_KEY }}" >> $GITHUB_ENV

      - name: Rodar OWASP Dependency Check
        run: mvn org.owasp:dependency-check-maven:check

      - name: Upload Relatório de Segurança OWASP
        uses: actions/upload-artifact@v4.4.3
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html

      - name: Rodar Análise de Dependências Maven 
        run: mvn snyk:test

      - name: Falhar build se houver vulnerabilidades críticas
        run: |
          if grep -q "CRITICAL" target/snyk-report.json; then
            echo "🚨 Vulnerabilidades críticas encontradas! 🚨"
            exit 1
          fi
